### PR TITLE
Fix handling of UTF-8 with bad locales

### LINKED ISSUE #8: Handling text encoding
> Is encoding of .nix file specified anywhere? For example, if it's UTF-8, this call may fail if C locale is set. Please double check. The same applies to formatStdio (there also TextIO.putStr probably can fail if C locale is set).

We should support other encodings, but we should also avoid failing on UTF-8 files when a different locale is set. Maybe we should try both when reading? I don't know how this is usually handled.

### LINKED ISSUE #11: Keyboard interrupt does not clean up temporary files
Currently, a keyboard interrupt is handled by immediately exiting. The temporary files created by `atomicWriteFile` are not cleaned up because of that. I have yet to figure out if the `atomic-write` library includes error handling to delete the file if it exits more gracefully.

### PR DESCRIPTION
**Pull request by kirelagin**
Fixes #8.
Fixes #11.

This PR adds a helper module (which is intended to eventually become a separate library) and changes the `nixfmt` binary to use functions from this new module for IO.

Specifically:

* If std{in,out,err} is terminal and the locale does not support UTF-8, it will transliterate (well, more like, replace with question marks) unsupported characters. The former two handles are used in the stdin/out processing mode, the latter is used for error reporting (errors can potentially include weird characters too).
* If std{in,out,err} is file, always assume it is in UTF-8.
* In the file processing mode, always assume files are in UTF-8.

## Test cases

```nix
# test.nix
let
 foo = "привет";
  in
   foo
```

These did not work before, now they do:
* `LANG=C nixfmt < test.nix`
* `LANG=C nixfmt < test.nix > out.nix`
* `LANG=C nixfmt text.nix`

### CODE REVIEW

**Comment by kirelagin** [comment]
@Lucus16 Let me know what you think about the atomic thing. How should we proceed? I would suggest we drop the library.

@gromakovsky @Martoon-00 Guys, pls, review, since you are now experts :).

**Comment by kirelagin** [comment]
@Lucus16 Of all the atomic write libraries I found on Hackage, this one is the only one that provides a sensible API: http://hackage.haskell.org/package/safeio-0.0.5.0/docs/System-IO-SafeWrite.html#v:withOutputFile

However, as far as I can tell, it does not copy any attributes, not even the mode. Even worse, it uses a system function to create the temporary file, and this function sets the mode to a very restricted one (only the owner can read). But the author got the interface right, so maybe we should contribute to it, or fork it, drop conduit, and make it preserve the attributes?

**Comment by kirelagin** [comment]
Ok, anyway, I reimplemented atomic write myself 🙄.

File: src/System/IO/Atomic.hs [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+import Control.Monad (when)
+import System.Directory (doesFileExist, removeFile, renameFile)
+import System.FilePath (takeDirectory, takeFileName)
+import System.IO (Handle, hClose, openTempFileWithDefaultPermissions)
+import System.Posix.Files (fileMode, getFileStatus, setFileMode)
+
+
+withOutputFile ::
+     FilePath  -- ^ Final file path
+  -> (Handle -> IO a)  -- ^ IO action that write to the file
```
Comment (gromakovsky) [inline src/System/IO/Atomic.hs]: s/write/writes

File: src/System/IO/Atomic.hs [hunk 2]
```diff
@@ -0,0 +1,49 @@
+{- © 2019 Serokell <hi@serokell.io>
+ -
+ - SPDX-License-Identifier: MPL-2.0
+ -}
+
+-- | Helpers for atomic file IO.
+--
+-- This module is a crossover of the `atomic-write` and `safeio` libraries
```
Comment (Lucus16) [inline src/System/IO/Atomic.hs]: I'd much rather you give a description of what this module does than where it comes from, since that's what I'd want to know if I were reading the documentation.

File: main/Main.hs [hunk 3]
```diff
@@ -40,8 +43,12 @@ formatStdio w = do
 
 formatFile :: Int -> FilePath -> IO Result
 formatFile w path = do
-    contents <- TextIO.readFile path
-    mapM (atomicWriteFile path) $ format w path contents
+    contents <- readFileUtf8 path
+    mapM atomicWriteFile $ format w path contents
+  where
+    atomicWriteFile t = withOutputFile path $ \h -> do
+      hSetEncoding h utf8
```
Comment (Lucus16) [inline main/Main.hs]: Is it possible to make the two new modules more composable so no implementation details leak here?

File: src/System/IO/Atomic.hs (hunk 2 above)
Comment (kirelagin) [reply src/System/IO/Atomic.hs]: > Helpers for atomic file IO.

Not good enough? 🤔

File: main/Main.hs (hunk 3 above)
Comment (kirelagin) [reply main/Main.hs]: I don’t think so, and I also don’t think any implementation details leak here. Correct handling of the data encoding is ultimately the responsibility of the programmer, the utf8 module just has helpers for frequently used tasks that can be considered “best practices”.

**Comment by kirelagin** [comment]
> Would be good to add tests to CI.
Indeed.

File: src/System/IO/Atomic.hs (hunk 2 above)
Comment (Lucus16) [reply src/System/IO/Atomic.hs]: > This module provides functions that ensure a file is written atomically by first writing the new contents to a temporary file. It also ensures this temporary file is cleaned up when an exception is raised.
Something like that.

File: main/Main.hs (hunk 3 above)
Comment (Lucus16) [reply main/Main.hs]: Okay, it can't be helped then.

**Comment by Lucus16** [comment]
The way I see it, the library should handle formatting and the executable should handle the CLI and filesystem interface.

**Comment by kirelagin** [comment]
Well, these two are supposed to be two separate libraries eventually anyway, sooo... I don’t think it matters at all, as long as we do not keep them here for too long. But feel free to move the to the executable if you think it’s better this way.

**Comment by kirelagin** [comment]
RE dependencies: I don’t think I introduced any dependencies that are not boot libraries.

File: main/System/IO/Atomic.hs [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+    copyAttributes (tpath, _th) = do
+      exists <- doesFileExist path
+      when exists $ do
+        getFileStatus path >>= setFileMode tpath . fileMode
+
+    commit :: (FilePath, Handle) -> IO ()
+    commit (tpath, th) = hClose th *> renameFile tpath path
+
+    rollback :: (FilePath, Handle) -> IO ()
+    rollback (tpath, th) = hClose th *> removeFile tpath
```
Comment (Martoon-00) [inline main/System/IO/Atomic.hs]: If `hClose` fails for some reason, full cleanup won't occur.

File: main/System/IO/Atomic.hs [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+-- it is Unix-specific and there is definitely room for improvement even on Unix.
+withOutputFile ::
+     FilePath  -- ^ Final file path
+  -> (Handle -> IO a)  -- ^ IO action that writes to the file
+  -> IO a
+withOutputFile path act = bracketOnError begin rollback $ \(tpath, th) -> do
+    copyAttributes (tpath, th)
+    result <- act th
+    commit (tpath, th)
+    pure result
```
[the remark this answers is not in the document]
Comment (kirelagin) [reply main/System/IO/Atomic.hs]: ouch

File: main/System/IO/Atomic.hs (hunk 4 above)
Comment (kirelagin) [reply main/System/IO/Atomic.hs]: Hmmm riiiight. I guess it shouldn’t matter in what order we do these two things, so it’s better to remove the file first, and close the handle after that?

File: main/System/IO/Atomic.hs (hunk 5 above)
[the remark this answers is not in the document]
Comment (kirelagin) [reply main/System/IO/Atomic.hs]: Or should I just implement my own bracket that masks both `commit` and `rollback`? What do you think?

[the remark this answers is not in the document]
Comment (Martoon-00) [reply main/System/IO/Atomic.hs]: Looks like less trivial but a more proper solution.

File: main/System/IO/Atomic.hs (hunk 4 above)
Comment (Martoon-00) [reply main/System/IO/Atomic.hs]: Wow, if it works then ok.

But can't `removeFile` fail as well? (probably in a very unlucky case like someone `rm -rf` the directory, but still).

Comment (kirelagin) [reply main/System/IO/Atomic.hs]: Ok, I am now not sure about this one. If `hClose` fails then we are probably in really deep trouble, and thus there is probably no need to try to recover or clean up or anything, we are screwed. 🤔

Comment (kirelagin) [reply main/System/IO/Atomic.hs]: Well, yes, `removeFile` can fails of course, e.g. if someone, as you say, removed this file before us, but I would speculate, that this is a condition worth reporting (i.e. we should let this exception propagate).

**Comment by kirelagin** [comment]
Oh, actually, it fixes #11 as well, what a coincidence!

File: main/System/IO/Atomic.hs (hunk 4 above)
Comment (Martoon-00) [reply main/System/IO/Atomic.hs]: Okay, let's leave it as is.

**Comment by Lucus16** [comment]
It's probably best to drop any exceptions in each of the parts of `rollback` since a more important exception is already being thrown.

**Comment by kirelagin** [comment]
> It's probably best to drop any exceptions in each of the parts of `rollback` since a more important exception is already being thrown.

Isn’t it how `onException` works?

**Comment by Lucus16** [comment]
What I mean that exceptions for each of the parts must be dropped since neither should prevent the other from being executed afaict.

**Comment by kirelagin** [comment]
No, I don’t think so 🤔. As I said in some comment thread, it is really weird if `hClose` fails, it means we are in a very-very serious trouble, so it’s probably better to stop trying. Also, I don’t think we want to drop those exceptions: as a programmer, I would prefer to know that my rollback action failed.

**Comment by kirelagin** [comment]
Oh, and, on a separate note, fuck my life, if I am reading it correctly, `onException` from `base` will actually rethrow the second exception, if it happens, not the first one. `onException` in `safe-exceptions` rethrows the first one in any case, though.

**Comment by Martoon-00** [comment]
Yeah, also find it weird. And `bracket` seem to inherit that behavior

**Comment by kirelagin** [comment]
Rebased.

**Comment by kirelagin** [comment]
Signed.
